version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Ho_Chi_Minh
    groups:
      npm-development-dependencies:
        dependency-type: development
      npm-production-dependencies:
        dependency-type: production
    open-pull-requests-limit: 5

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      timezone: Asia/Ho_Chi_Minh
    groups:
      github-actions:
        patterns:
          - '*'
    open-pull-requests-limit: 3
